2025-05-15 20:38:23,098 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.761778°N, 73.985932°W
2025-05-15 20:38:28,295 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-15 20:51:40,001 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.717478°N, 74.006928°W
2025-05-15 20:51:40,142 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-15 21:00:54,513 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.755675°N, 73.976909°W
2025-05-15 21:01:03,058 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.732760°N, 74.011559°W
2025-05-15 21:01:03,399 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-15 21:06:28,396 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.762952°N, 74.042149°W
2025-05-15 21:06:28,549 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-15 21:14:17,236 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.703065°N, 73.974548°W
2025-05-15 21:14:17,461 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-15 21:29:39,970 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.726642°N, 74.042631°W
2025-05-15 21:29:40,167 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-15 21:35:02,013 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.758110°N, 73.992186°W
2025-05-15 21:35:02,266 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-15 21:39:40,508 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.768760°N, 73.994384°W
2025-05-15 21:39:40,766 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-15 21:51:34,195 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.752132°N, 73.994487°W
2025-05-15 21:51:34,349 [ERROR] night_agent.AGENT009: Error al conectar con el servidor: name 'RabbitMQConsumer' is not defined
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 81, in connect
    self.comm_client = RabbitMQConsumer(
                       ^^^^^^^^^^^^^^^^
NameError: name 'RabbitMQConsumer' is not defined
2025-05-15 21:51:34,355 [ERROR] night_agent.AGENT009: Error en el agente AGENT009: name 'RabbitMQConsumer' is not defined
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 285, in run
    self.connect()
    ~~~~~~~~~~~~^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 81, in connect
    self.comm_client = RabbitMQConsumer(
                       ^^^^^^^^^^^^^^^^
NameError: name 'RabbitMQConsumer' is not defined
2025-05-15 21:51:34,361 [INFO] night_agent.AGENT009: Deteniendo agente AGENT009
2025-05-15 21:51:34,367 [INFO] night_agent.AGENT009: Cerrada conexión del publisher
2025-05-15 21:51:34,367 [INFO] night_agent.AGENT009: Agente AGENT009 finalizado
2025-05-15 21:53:42,231 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.731526°N, 73.979105°W
2025-05-15 21:53:42,309 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-15 21:57:52,004 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.743461°N, 74.005871°W
2025-05-15 21:57:52,382 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-15 22:07:34,556 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.797566°N, 73.993735°W
2025-05-15 22:07:34,745 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-15 22:25:38,676 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.765405°N, 73.950472°W
2025-05-15 22:25:38,791 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-15 22:27:42,891 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.751884°N, 74.041592°W
2025-05-15 22:27:42,970 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-15 22:31:42,425 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.761370°N, 73.961726°W
2025-05-15 22:31:42,685 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-15 22:48:41,789 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.726294°N, 74.031701°W
2025-05-15 22:48:42,119 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-15 22:54:57,701 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.784173°N, 73.950619°W
2025-05-15 22:54:57,781 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-15 23:04:42,678 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.741782°N, 74.008075°W
2025-05-15 23:04:42,775 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-15 23:10:10,534 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.791657°N, 73.982723°W
2025-05-15 23:10:10,663 [ERROR] night_agent.AGENT009: Error al conectar con el servidor: RabbitMQConsumer.__init__() got an unexpected keyword argument 'auto_ack'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 61, in connect
    self.comm_client = RabbitMQConsumer(
                       ~~~~~~~~~~~~~~~~^
        host=config.RABBITMQ_HOST,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
        auto_ack=False  # Importante: no confirmar automáticamente
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
TypeError: RabbitMQConsumer.__init__() got an unexpected keyword argument 'auto_ack'
2025-05-15 23:10:10,668 [ERROR] night_agent.AGENT009: Error en el agente AGENT009: RabbitMQConsumer.__init__() got an unexpected keyword argument 'auto_ack'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 253, in run
    self.connect()
    ~~~~~~~~~~~~^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 61, in connect
    self.comm_client = RabbitMQConsumer(
                       ~~~~~~~~~~~~~~~~^
        host=config.RABBITMQ_HOST,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
        auto_ack=False  # Importante: no confirmar automáticamente
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
TypeError: RabbitMQConsumer.__init__() got an unexpected keyword argument 'auto_ack'
2025-05-15 23:10:10,669 [INFO] night_agent.AGENT009: Deteniendo agente AGENT009
2025-05-15 23:10:10,679 [INFO] night_agent.AGENT009: Cerrada conexión del publisher
2025-05-15 23:10:10,679 [INFO] night_agent.AGENT009: Agente AGENT009 finalizado
2025-05-15 23:25:17,396 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.729521°N, 74.019874°W
2025-05-15 23:25:17,653 [ERROR] night_agent.AGENT009: Error al conectar con el servidor: RabbitMQConsumer.__init__() got an unexpected keyword argument 'auto_ack'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 61, in connect
    self.comm_client = RabbitMQConsumer(
                       ~~~~~~~~~~~~~~~~^
        host=config.RABBITMQ_HOST,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
        auto_ack=False  # Importante: no confirmar automáticamente
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
TypeError: RabbitMQConsumer.__init__() got an unexpected keyword argument 'auto_ack'
2025-05-15 23:25:17,656 [ERROR] night_agent.AGENT009: Error en el agente AGENT009: RabbitMQConsumer.__init__() got an unexpected keyword argument 'auto_ack'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 253, in run
    self.connect()
    ~~~~~~~~~~~~^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 61, in connect
    self.comm_client = RabbitMQConsumer(
                       ~~~~~~~~~~~~~~~~^
        host=config.RABBITMQ_HOST,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
        auto_ack=False  # Importante: no confirmar automáticamente
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
TypeError: RabbitMQConsumer.__init__() got an unexpected keyword argument 'auto_ack'
2025-05-15 23:25:17,657 [INFO] night_agent.AGENT009: Deteniendo agente AGENT009
2025-05-15 23:25:17,663 [INFO] night_agent.AGENT009: Cerrada conexión del publisher
2025-05-15 23:25:17,663 [INFO] night_agent.AGENT009: Agente AGENT009 finalizado
2025-05-15 23:30:59,176 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.756116°N, 73.951109°W
2025-05-15 23:30:59,329 [ERROR] night_agent.AGENT009: Error al conectar con el servidor: RabbitMQConsumer.__init__() got an unexpected keyword argument 'auto_ack'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 61, in connect
    self.comm_client = RabbitMQConsumer(
                       ~~~~~~~~~~~~~~~~^
        host=config.RABBITMQ_HOST,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
        auto_ack=False  # Importante: no confirmar automáticamente
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
TypeError: RabbitMQConsumer.__init__() got an unexpected keyword argument 'auto_ack'
2025-05-15 23:30:59,330 [ERROR] night_agent.AGENT009: Error en el agente AGENT009: RabbitMQConsumer.__init__() got an unexpected keyword argument 'auto_ack'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 253, in run
    self.connect()
    ~~~~~~~~~~~~^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 61, in connect
    self.comm_client = RabbitMQConsumer(
                       ~~~~~~~~~~~~~~~~^
        host=config.RABBITMQ_HOST,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
        auto_ack=False  # Importante: no confirmar automáticamente
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
TypeError: RabbitMQConsumer.__init__() got an unexpected keyword argument 'auto_ack'
2025-05-15 23:30:59,339 [INFO] night_agent.AGENT009: Deteniendo agente AGENT009
2025-05-15 23:30:59,350 [INFO] night_agent.AGENT009: Cerrada conexión del publisher
2025-05-15 23:30:59,350 [INFO] night_agent.AGENT009: Agente AGENT009 finalizado
2025-05-15 23:32:43,733 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.765255°N, 73.965954°W
2025-05-15 23:32:43,884 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-15 23:32:43,884 [ERROR] night_agent.AGENT009: Error en el agente AGENT009: 'NoneType' object has no attribute 'basic_qos'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 257, in run
    self.comm_client.channel.basic_qos(prefetch_count=1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'basic_qos'
2025-05-15 23:32:43,887 [INFO] night_agent.AGENT009: Deteniendo agente AGENT009
2025-05-15 23:32:43,887 [INFO] night_agent.AGENT009: Desconectado del servidor
2025-05-15 23:32:43,895 [INFO] night_agent.AGENT009: Cerrada conexión del publisher
2025-05-15 23:32:43,896 [INFO] night_agent.AGENT009: Agente AGENT009 finalizado
2025-05-15 23:34:56,205 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.753529°N, 73.954512°W
2025-05-15 23:34:56,420 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-15 23:36:19,080 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.733193°N, 73.952293°W
2025-05-15 23:36:19,289 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-15 23:38:13,601 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.798913°N, 74.041906°W
2025-05-15 23:38:13,805 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-15 23:40:03,854 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.747919°N, 73.971955°W
2025-05-15 23:40:03,981 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-15 23:43:11,338 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.779564°N, 73.984826°W
2025-05-15 23:43:11,524 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-15 23:46:38,659 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.739093°N, 73.996610°W
2025-05-15 23:46:38,803 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-15 23:50:01,761 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.733156°N, 74.022018°W
2025-05-15 23:50:01,961 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-15 23:55:35,877 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.707857°N, 74.019164°W
2025-05-15 23:55:36,035 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-15 23:59:48,406 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.746360°N, 74.022503°W
2025-05-15 23:59:48,550 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-16 00:05:20,946 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.734210°N, 73.994803°W
2025-05-16 00:05:21,120 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-16 00:13:09,583 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.759469°N, 74.047203°W
2025-05-16 00:13:09,706 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-16 00:13:09,707 [ERROR] night_agent.AGENT009: Error en el agente AGENT009: 'NoneType' object has no attribute 'start_consuming'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 245, in run
    self.comm_client.start_consuming(callback=self.handle_task)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'start_consuming'
2025-05-16 00:13:09,709 [INFO] night_agent.AGENT009: Deteniendo agente AGENT009
2025-05-16 00:13:09,717 [INFO] night_agent.AGENT009: Cerrada conexión del publisher
2025-05-16 00:13:09,717 [INFO] night_agent.AGENT009: Agente AGENT009 finalizado
2025-05-16 00:18:17,064 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.746764°N, 73.996049°W
2025-05-16 00:18:17,406 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-16 00:22:01,681 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.734612°N, 74.017026°W
2025-05-16 00:22:02,068 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-16 00:24:22,356 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.766002°N, 74.009799°W
2025-05-16 00:24:22,558 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-16 00:28:44,703 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.743236°N, 73.999211°W
2025-05-16 00:28:44,803 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-16 00:28:44,808 [ERROR] night_agent.AGENT009: Error al enviar estado: 'NoneType' object has no attribute 'publish_message'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 96, in send_status_update
    self.publisher.publish_message(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'publish_message'
2025-05-16 00:33:49,691 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.735042°N, 73.952248°W
2025-05-16 00:33:49,946 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-16 00:33:49,954 [ERROR] night_agent.AGENT009: Error al enviar estado: 'NoneType' object has no attribute 'publish_message'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 96, in send_status_update
    self.publisher.publish_message(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'publish_message'
2025-05-16 00:35:21,756 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.731652°N, 74.033194°W
2025-05-16 00:35:21,871 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-16 00:35:21,876 [ERROR] night_agent.AGENT009: Error al enviar estado: 'NoneType' object has no attribute 'publish_message'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 96, in send_status_update
    self.publisher.publish_message(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'publish_message'
2025-05-16 09:43:05,229 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.735199°N, 74.023477°W
2025-05-16 09:43:05,379 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-16 09:43:05,395 [ERROR] night_agent.AGENT009: Error al enviar estado: 'NoneType' object has no attribute 'publish_message'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 95, in send_status_update
    self.publisher.publish_message(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'publish_message'
2025-05-16 10:00:03,156 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.754569°N, 73.991055°W
2025-05-16 10:00:03,296 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-16 10:00:03,299 [ERROR] night_agent.AGENT009: Error al enviar estado: 'NoneType' object has no attribute 'publish_message'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 94, in send_status_update
    self.publisher.publish_message(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'publish_message'
2025-05-16 10:08:24,437 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.767907°N, 73.959907°W
2025-05-16 10:08:24,529 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-16 10:08:24,533 [ERROR] night_agent.AGENT009: Error al enviar estado: 'NoneType' object has no attribute 'publish_message'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 94, in send_status_update
    self.publisher.publish_message(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'publish_message'
2025-05-16 10:14:26,697 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.744035°N, 74.030597°W
2025-05-16 10:14:26,697 [ERROR] night_agent.AGENT009: Error al conectar con el servidor: RabbitMQConsumer.__init__() got an unexpected keyword argument 'on_message_callback'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 50, in connect
    self.comm_client = RabbitMQConsumer(
                       ~~~~~~~~~~~~~~~~^
        host=config.RABBITMQ_HOST,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
        binding_keys=['task.broadcast']
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
TypeError: RabbitMQConsumer.__init__() got an unexpected keyword argument 'on_message_callback'
2025-05-16 10:14:26,699 [ERROR] night_agent.AGENT009: Error en el agente AGENT009: RabbitMQConsumer.__init__() got an unexpected keyword argument 'on_message_callback'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 255, in run
    self.connect()
    ~~~~~~~~~~~~^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 50, in connect
    self.comm_client = RabbitMQConsumer(
                       ~~~~~~~~~~~~~~~~^
        host=config.RABBITMQ_HOST,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
        binding_keys=['task.broadcast']
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
TypeError: RabbitMQConsumer.__init__() got an unexpected keyword argument 'on_message_callback'
2025-05-16 10:14:26,700 [INFO] night_agent.AGENT009: Deteniendo agente AGENT009
2025-05-16 10:14:26,700 [INFO] night_agent.AGENT009: Agente AGENT009 finalizado
2025-05-16 10:19:54,063 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.784702°N, 73.978543°W
2025-05-16 10:19:54,064 [ERROR] night_agent.AGENT009: Error al conectar con el servidor: RabbitMQConsumer.__init__() got an unexpected keyword argument 'on_message_callback'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 50, in connect
    self.comm_client = RabbitMQConsumer(
                       ~~~~~~~~~~~~~~~~^
        host=config.RABBITMQ_HOST,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
        binding_keys=['task.broadcast']
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
TypeError: RabbitMQConsumer.__init__() got an unexpected keyword argument 'on_message_callback'
2025-05-16 10:19:54,066 [ERROR] night_agent.AGENT009: Error en el agente AGENT009: RabbitMQConsumer.__init__() got an unexpected keyword argument 'on_message_callback'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 262, in run
    self.connect()
    ~~~~~~~~~~~~^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 50, in connect
    self.comm_client = RabbitMQConsumer(
                       ~~~~~~~~~~~~~~~~^
        host=config.RABBITMQ_HOST,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
        binding_keys=['task.broadcast']
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
TypeError: RabbitMQConsumer.__init__() got an unexpected keyword argument 'on_message_callback'
2025-05-16 10:19:54,067 [INFO] night_agent.AGENT009: Deteniendo agente AGENT009
2025-05-16 10:19:54,067 [INFO] night_agent.AGENT009: Agente AGENT009 finalizado
2025-05-16 10:22:13,166 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.780020°N, 74.036350°W
2025-05-16 10:22:13,295 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-16 10:22:13,295 [ERROR] night_agent.AGENT009: Error al enviar estado: 'NoneType' object has no attribute 'publish_message'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 117, in send_status_update
    self.publisher.publish_message(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'publish_message'
2025-05-16 10:28:21,109 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.703158°N, 73.987250°W
2025-05-16 10:28:21,266 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-16 10:28:21,266 [ERROR] night_agent.AGENT009: Error al enviar estado: 'NoneType' object has no attribute 'publish_message'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 118, in send_status_update
    self.publisher.publish_message(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'publish_message'
2025-05-16 10:36:29,143 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.724505°N, 73.979455°W
2025-05-16 10:36:29,359 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-16 10:36:29,359 [ERROR] night_agent.AGENT009: Error al enviar estado: cannot access local variable 'properties' where it is not associated with a value
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 151, in send_status_update
    self.publisher.publish_message(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        message,
        ^^^^^^^^
        routing_key='task.broadcast'
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 135, in publish_message
    properties=properties
               ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'properties' where it is not associated with a value
2025-05-16 10:39:56,248 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.746754°N, 74.002260°W
2025-05-16 10:39:56,522 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-16 10:44:23,712 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.770121°N, 73.968858°W
2025-05-16 10:44:24,063 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-16 10:47:57,243 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.710145°N, 74.003586°W
2025-05-16 10:47:57,490 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-16 10:47:57,665 [ERROR] night_agent.AGENT009: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:47:57,668 [ERROR] night_agent.AGENT009: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:47:57,784 [ERROR] night_agent.AGENT009: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:47:57,785 [ERROR] night_agent.AGENT009: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:48:09,427 [ERROR] night_agent.AGENT009: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:48:09,428 [ERROR] night_agent.AGENT009: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:48:15,847 [ERROR] night_agent.AGENT009: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:48:15,847 [ERROR] night_agent.AGENT009: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:48:19,869 [ERROR] night_agent.AGENT009: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:48:19,870 [ERROR] night_agent.AGENT009: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:48:27,365 [ERROR] night_agent.AGENT009: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:48:27,366 [ERROR] night_agent.AGENT009: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:48:33,966 [ERROR] night_agent.AGENT009: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:48:33,966 [ERROR] night_agent.AGENT009: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:48:41,365 [ERROR] night_agent.AGENT009: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:48:41,366 [ERROR] night_agent.AGENT009: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:48:49,321 [ERROR] night_agent.AGENT009: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:48:49,322 [ERROR] night_agent.AGENT009: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:48:55,065 [ERROR] night_agent.AGENT009: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:48:55,066 [ERROR] night_agent.AGENT009: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:49:00,108 [ERROR] night_agent.AGENT009: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:49:00,108 [ERROR] night_agent.AGENT009: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:49:07,072 [ERROR] night_agent.AGENT009: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:49:07,072 [ERROR] night_agent.AGENT009: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:49:11,878 [ERROR] night_agent.AGENT009: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:49:11,879 [ERROR] night_agent.AGENT009: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:49:17,022 [ERROR] night_agent.AGENT009: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:49:17,022 [ERROR] night_agent.AGENT009: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:49:24,720 [ERROR] night_agent.AGENT009: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:49:24,721 [ERROR] night_agent.AGENT009: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:49:32,774 [ERROR] night_agent.AGENT009: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:49:32,775 [ERROR] night_agent.AGENT009: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:49:37,966 [ERROR] night_agent.AGENT009: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:49:37,966 [ERROR] night_agent.AGENT009: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:49:43,647 [ERROR] night_agent.AGENT009: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:49:43,648 [ERROR] night_agent.AGENT009: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:49:48,731 [ERROR] night_agent.AGENT009: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:49:48,731 [ERROR] night_agent.AGENT009: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:49:57,247 [ERROR] night_agent.AGENT009: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:49:57,247 [ERROR] night_agent.AGENT009: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:50:02,686 [ERROR] night_agent.AGENT009: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:50:02,687 [ERROR] night_agent.AGENT009: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:50:08,930 [ERROR] night_agent.AGENT009: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:50:08,931 [ERROR] night_agent.AGENT009: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:50:15,829 [ERROR] night_agent.AGENT009: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:50:15,830 [ERROR] night_agent.AGENT009: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:50:21,939 [ERROR] night_agent.AGENT009: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:50:21,940 [ERROR] night_agent.AGENT009: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:50:29,091 [ERROR] night_agent.AGENT009: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:50:29,091 [ERROR] night_agent.AGENT009: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:50:36,854 [ERROR] night_agent.AGENT009: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:50:36,855 [ERROR] night_agent.AGENT009: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:50:41,539 [ERROR] night_agent.AGENT009: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:50:41,540 [ERROR] night_agent.AGENT009: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:50:48,272 [ERROR] night_agent.AGENT009: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:50:48,273 [ERROR] night_agent.AGENT009: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:50:50,903 [ERROR] night_agent.AGENT009: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:50:50,904 [ERROR] night_agent.AGENT009: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:50:50,918 [ERROR] night_agent.AGENT009: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:50:50,919 [ERROR] night_agent.AGENT009: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:50:58,953 [ERROR] night_agent.AGENT009: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:50:58,953 [ERROR] night_agent.AGENT009: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:51:07,136 [ERROR] night_agent.AGENT009: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:51:07,136 [ERROR] night_agent.AGENT009: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:51:13,071 [ERROR] night_agent.AGENT009: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:51:13,072 [ERROR] night_agent.AGENT009: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:51:20,292 [ERROR] night_agent.AGENT009: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:51:20,293 [ERROR] night_agent.AGENT009: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:51:25,829 [ERROR] night_agent.AGENT009: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:51:25,830 [ERROR] night_agent.AGENT009: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:51:31,333 [ERROR] night_agent.AGENT009: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:51:31,333 [ERROR] night_agent.AGENT009: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:51:36,411 [ERROR] night_agent.AGENT009: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:51:36,411 [ERROR] night_agent.AGENT009: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:51:44,380 [ERROR] night_agent.AGENT009: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:51:44,381 [ERROR] night_agent.AGENT009: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:51:50,840 [ERROR] night_agent.AGENT009: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:51:50,840 [ERROR] night_agent.AGENT009: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:51:57,576 [ERROR] night_agent.AGENT009: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:51:57,576 [ERROR] night_agent.AGENT009: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:52:03,721 [ERROR] night_agent.AGENT009: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:52:03,722 [ERROR] night_agent.AGENT009: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:52:10,108 [ERROR] night_agent.AGENT009: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:52:10,108 [ERROR] night_agent.AGENT009: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:52:14,668 [ERROR] night_agent.AGENT009: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:52:14,669 [ERROR] night_agent.AGENT009: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:53:21,613 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.785330°N, 73.968990°W
2025-05-16 10:53:21,917 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-16 10:53:21,950 [ERROR] night_agent.AGENT009: Error procesando tarea: name 'create_message_from_json' is not defined
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 129, in handle_task
    task = create_message_from_json(task_json)
           ^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'create_message_from_json' is not defined
2025-05-16 10:53:27,341 [ERROR] night_agent.AGENT009: Error procesando tarea: name 'create_message_from_json' is not defined
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 129, in handle_task
    task = create_message_from_json(task_json)
           ^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'create_message_from_json' is not defined
2025-05-16 10:53:30,057 [ERROR] night_agent.AGENT009: Error procesando tarea: name 'create_message_from_json' is not defined
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 129, in handle_task
    task = create_message_from_json(task_json)
           ^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'create_message_from_json' is not defined
2025-05-16 10:53:30,069 [ERROR] night_agent.AGENT009: Error procesando tarea: name 'create_message_from_json' is not defined
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 129, in handle_task
    task = create_message_from_json(task_json)
           ^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'create_message_from_json' is not defined
2025-05-16 10:55:36,842 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.793503°N, 74.006255°W
2025-05-16 10:55:37,188 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-16 10:55:37,204 [INFO] night_agent.AGENT009: Tarea recibida: AlertMessage(message_id='8425df3a-c59c-40ea-943b-b72df8d93a59', timestamp=1747385737.1505108, message_type='ALERT', sender_id='SPY009', position=(40.724901, -73.983465), emergency_level='BAJA', emergency_type='AMENAZA_BOMBA', description='')
2025-05-16 10:55:49,254 [INFO] night_agent.AGENT009: Tarea recibida: AlertMessage(message_id='97bf008e-2a34-4d06-a870-ff11abfe430f', timestamp=1747385749.2516448, message_type='ALERT', sender_id='SPY007', position=(40.72974856783396, -74.02293131260251), emergency_level='CRÍTICA', emergency_type='AMENAZA_BOMBA', description='')
2025-05-16 10:55:55,717 [INFO] night_agent.AGENT009: Tarea recibida: AlertMessage(message_id='abb2e11a-3a87-48c1-9556-ea7c2bc0f5aa', timestamp=1747385755.7147787, message_type='ALERT', sender_id='SPY019', position=(40.7017530400832, -73.97125577774936), emergency_level='CRÍTICA', emergency_type='VIGILANCIA', description='')
2025-05-16 10:56:02,159 [INFO] night_agent.AGENT009: Tarea recibida: AlertMessage(message_id='b9e79045-3034-4026-a2a8-9d92dd57aa81', timestamp=1747385762.1569874, message_type='ALERT', sender_id='SPY007', position=(40.73017065847499, -74.0234490731674), emergency_level='MEDIA', emergency_type='AMENAZA_BOMBA', description='')
2025-05-16 10:56:07,419 [INFO] night_agent.AGENT009: Tarea recibida: AlertMessage(message_id='a16f1ca2-90dd-47bb-94df-fafc083e99d4', timestamp=1747385767.4169407, message_type='ALERT', sender_id='SPY014', position=(40.71115156895691, -74.0274554183642), emergency_level='BAJA', emergency_type='ROBO', description='')
2025-05-16 10:56:13,729 [INFO] night_agent.AGENT009: Tarea recibida: AlertMessage(message_id='2b682a8f-8e7b-4958-ba73-2552f48d272a', timestamp=1747385773.727426, message_type='ALERT', sender_id='SPY018', position=(40.718762055660015, -74.01723084394428), emergency_level='CRÍTICA', emergency_type='SECUESTRO', description='')
2025-05-16 10:56:16,218 [INFO] night_agent.AGENT009: Tarea recibida: AlertMessage(message_id='41dde86f-0996-4d72-93ff-2bc7fe49191f', timestamp=1747385776.2125635, message_type='ALERT', sender_id='SPY016', position=(40.72559266731219, -73.977247608612), emergency_level='ALTA', emergency_type='SECUESTRO', description='')
2025-05-16 10:56:16,224 [INFO] night_agent.AGENT009: Tarea recibida: AlertMessage(message_id='8a2cffdc-4ae1-4c5b-b730-e571c4ae6a7d', timestamp=1747385776.2125955, message_type='ALERT', sender_id='SPY015', position=(40.74896940595299, -73.98594355238909), emergency_level='BAJA', emergency_type='INTRUSIÓN', description='')
2025-05-16 14:21:44,719 [INFO] night_agent.AGENT009: Agente AGENT009 inicializado en posición 40.771398°N, 74.002877°W
2025-05-16 14:21:45,149 [INFO] night_agent.AGENT009: Conectado al servidor usando rabbitmq
2025-05-16 14:21:45,235 [INFO] night_agent.AGENT009: Tarea recibida: AlertMessage(message_id='2ffae808-643e-4898-bca5-1387a6cc3914', timestamp=1747398105.1866138, message_type='ALERT', sender_id='SPY013', position=(40.767578, -74.02609), emergency_level='ALTA', emergency_type='ROBO', description='')
2025-05-16 14:21:52,428 [INFO] night_agent.AGENT009: Tarea recibida: AlertMessage(message_id='52fed7f4-c531-46ec-a292-3197d61ec7f4', timestamp=1747398112.4246645, message_type='ALERT', sender_id='SPY019', position=(40.719106699436075, -74.02526310696491), emergency_level='BAJA', emergency_type='INTRUSIÓN', description='')
2025-05-16 14:21:56,724 [INFO] night_agent.AGENT009: Tarea recibida: AlertMessage(message_id='2897778a-4983-43d8-88ad-933d911ab626', timestamp=1747398116.7202454, message_type='ALERT', sender_id='SPY016', position=(40.70437312840735, -73.95125547756116), emergency_level='BAJA', emergency_type='VIGILANCIA', description='')
2025-05-16 14:22:03,159 [INFO] night_agent.AGENT009: Tarea recibida: AlertMessage(message_id='48b473b0-c81e-42c8-8ca6-4ccf79a35005', timestamp=1747398123.154203, message_type='ALERT', sender_id='SPY004', position=(40.732821024967926, -73.98484672053705), emergency_level='ALTA', emergency_type='ROBO', description='')
2025-05-16 14:22:08,616 [INFO] night_agent.AGENT009: Tarea recibida: AlertMessage(message_id='0d6f368d-66c9-48d3-8c52-b2d11d71f807', timestamp=1747398128.6122901, message_type='ALERT', sender_id='SPY020', position=(40.7011137231693, -73.99976724018107), emergency_level='ALTA', emergency_type='AMENAZA_BOMBA', description='')
2025-05-16 14:22:16,754 [INFO] night_agent.AGENT009: Tarea recibida: AlertMessage(message_id='9a2b9e10-ccbd-4dd8-91b8-36268b3a7cd6', timestamp=1747398136.7495596, message_type='ALERT', sender_id='SPY005', position=(40.70630733598913, -73.96713611578706), emergency_level='BAJA', emergency_type='VIGILANCIA', description='')
2025-05-16 14:22:20,836 [INFO] night_agent.AGENT009: Tarea recibida: AlertMessage(message_id='8f76a898-e7fe-4492-8aa2-3386589ec9a7', timestamp=1747398140.8311281, message_type='ALERT', sender_id='SPY002', position=(40.70230906070896, -73.98290222495707), emergency_level='ALTA', emergency_type='AMENAZA_BOMBA', description='')
2025-05-16 14:22:27,797 [INFO] night_agent.AGENT009: Tarea recibida: AlertMessage(message_id='a849b4ca-4026-418b-86d0-b628eecd5441', timestamp=1747398147.7927098, message_type='ALERT', sender_id='SPY002', position=(40.702817233794605, -73.98242116568498), emergency_level='CRÍTICA', emergency_type='AMENAZA_BOMBA', description='')
2025-05-16 14:22:34,568 [INFO] night_agent.AGENT009: Tarea recibida: AlertMessage(message_id='28f02360-55ca-4b00-9b09-bf11abc4c1a2', timestamp=1747398154.5639577, message_type='ALERT', sender_id='SPY004', position=(40.73276195801115, -73.98538157124602), emergency_level='CRÍTICA', emergency_type='AMENAZA_BOMBA', description='')
2025-05-16 14:22:38,673 [INFO] night_agent.AGENT009: Tarea recibida: AlertMessage(message_id='76cbbbb8-c519-4c9c-a874-771d22cf75c3', timestamp=1747398158.6697035, message_type='ALERT', sender_id='SPY001', position=(40.78150620717293, -74.01072696550006), emergency_level='MEDIA', emergency_type='INTRUSIÓN', description='')
2025-05-16 14:22:46,083 [INFO] night_agent.AGENT009: Tarea recibida: AlertMessage(message_id='f2e38453-4376-44e8-baf8-f75bb90bec97', timestamp=1747398166.076517, message_type='ALERT', sender_id='SPY018', position=(40.73039038486946, -73.95997599547522), emergency_level='MEDIA', emergency_type='INTRUSIÓN', description='')
2025-05-16 14:22:51,663 [INFO] night_agent.AGENT009: Tarea recibida: AlertMessage(message_id='ae3719de-4bc1-4a05-a32e-2a9f3b3cb331', timestamp=1747398171.658551, message_type='ALERT', sender_id='SPY020', position=(40.70171134311291, -73.99867538721614), emergency_level='BAJA', emergency_type='ROBO', description='')
2025-05-16 14:22:59,005 [INFO] night_agent.AGENT009: Tarea recibida: AlertMessage(message_id='8a66e461-bad9-4466-89e0-c327df818725', timestamp=1747398179.0003579, message_type='ALERT', sender_id='SPY018', position=(40.73056055362394, -73.96031963163014), emergency_level='BAJA', emergency_type='AMENAZA_BOMBA', description='')
2025-05-16 14:23:04,628 [INFO] night_agent.AGENT009: Tarea recibida: AlertMessage(message_id='73ac46a1-4964-4ca7-b4a0-fb62a5841f35', timestamp=1747398184.6238213, message_type='ALERT', sender_id='SPY005', position=(40.707334005778606, -73.9666356941086), emergency_level='MEDIA', emergency_type='VIGILANCIA', description='')
2025-05-16 14:23:12,575 [INFO] night_agent.AGENT009: Tarea recibida: AlertMessage(message_id='05928d45-dfb5-4fcb-a532-bcc7d059fd68', timestamp=1747398192.5715148, message_type='ALERT', sender_id='SPY013', position=(40.76798424204409, -74.02679492580003), emergency_level='BAJA', emergency_type='INTRUSIÓN', description='')
2025-05-16 14:23:17,663 [INFO] night_agent.AGENT009: Tarea recibida: AlertMessage(message_id='4813f4eb-955d-4380-bc3a-e65dc029bd75', timestamp=1747398197.6589901, message_type='ALERT', sender_id='SPY002', position=(40.702528137674925, -73.98391453030334), emergency_level='CRÍTICA', emergency_type='INTRUSIÓN', description='')
2025-05-16 14:23:22,461 [INFO] night_agent.AGENT009: Tarea recibida: AlertMessage(message_id='cb7eccf5-bca5-4bec-bf3e-c6c24d15df40', timestamp=1747398202.4570363, message_type='ALERT', sender_id='SPY017', position=(40.75207558768204, -74.02052898882528), emergency_level='ALTA', emergency_type='ROBO', description='')
2025-05-16 14:23:29,572 [INFO] night_agent.AGENT009: Tarea recibida: AlertMessage(message_id='1ec38014-b889-4e70-9f02-ff301b501527', timestamp=1747398209.5681946, message_type='ALERT', sender_id='SPY003', position=(40.712292523059574, -73.96431366142706), emergency_level='BAJA', emergency_type='AMENAZA_BOMBA', description='')
2025-05-16 14:23:38,095 [INFO] night_agent.AGENT009: Tarea recibida: AlertMessage(message_id='2f1643bf-5cb9-47e7-ae5f-1d69abdffcd4', timestamp=1747398218.0910654, message_type='ALERT', sender_id='SPY003', position=(40.712556376195884, -73.964870836844), emergency_level='BAJA', emergency_type='AMENAZA_BOMBA', description='')
2025-05-16 14:23:42,735 [INFO] night_agent.AGENT009: Tarea recibida: AlertMessage(message_id='4e9293b1-3346-49d4-9c47-c31c33086185', timestamp=1747398222.7311754, message_type='ALERT', sender_id='SPY014', position=(40.74453167449367, -73.95134591297885), emergency_level='CRÍTICA', emergency_type='AMENAZA_BOMBA', description='')
2025-05-16 14:23:46,463 [INFO] night_agent.AGENT009: Tarea recibida: AlertMessage(message_id='f683f65e-d05d-4063-8548-59f84b608559', timestamp=1747398226.4589329, message_type='ALERT', sender_id='SPY018', position=(40.72863309232092, -73.9608021019712), emergency_level='ALTA', emergency_type='VIGILANCIA', description='')
2025-05-16 14:23:54,974 [INFO] night_agent.AGENT009: Tarea recibida: AlertMessage(message_id='93caf622-c617-401f-8de1-84c6f145e3cc', timestamp=1747398234.9700527, message_type='ALERT', sender_id='SPY020', position=(40.70061707565275, -73.99789182666643), emergency_level='CRÍTICA', emergency_type='VIGILANCIA', description='')
2025-05-16 14:24:00,901 [INFO] night_agent.AGENT009: Tarea recibida: AlertMessage(message_id='1ce714b4-613d-449c-82f6-c06e06d40917', timestamp=1747398240.8975654, message_type='ALERT', sender_id='SPY015', position=(40.716335364984225, -73.97100624271957), emergency_level='BAJA', emergency_type='ROBO', description='')
2025-05-16 14:24:06,281 [INFO] night_agent.AGENT009: Tarea recibida: AlertMessage(message_id='839311a0-e222-42e6-98a0-cd2a01483729', timestamp=1747398246.276223, message_type='ALERT', sender_id='SPY015', position=(40.71616892056954, -73.97133482382186), emergency_level='MEDIA', emergency_type='INTRUSIÓN', description='')
2025-05-16 14:24:16,164 [INFO] night_agent.AGENT009: Tarea recibida: AlertMessage(message_id='26f4bb03-0ca2-4b3f-90a3-8fe9a12c98f2', timestamp=1747398256.1604626, message_type='ALERT', sender_id='SPY013', position=(40.76903454716841, -74.02506261694565), emergency_level='MEDIA', emergency_type='INTRUSIÓN', description='')
2025-05-16 14:24:19,820 [INFO] night_agent.AGENT009: Tarea recibida: AlertMessage(message_id='6820ac70-4b0b-46b7-ab53-0f1a6da05e73', timestamp=1747398259.8163502, message_type='ALERT', sender_id='SPY019', position=(40.71935880872623, -74.02623564777336), emergency_level='CRÍTICA', emergency_type='VIGILANCIA', description='')
2025-05-16 14:24:27,897 [INFO] night_agent.AGENT009: Tarea recibida: AlertMessage(message_id='7839d210-9c37-4cf4-bd47-b99a28929c62', timestamp=1747398267.8928678, message_type='ALERT', sender_id='SPY006', position=(40.70973609465813, -73.99746643053516), emergency_level='MEDIA', emergency_type='VIGILANCIA', description='')
2025-05-16 14:24:33,299 [INFO] night_agent.AGENT009: Tarea recibida: AlertMessage(message_id='3465cbce-aba0-4a68-960c-ebcf460c9e24', timestamp=1747398273.2951334, message_type='ALERT', sender_id='SPY001', position=(40.78360350776425, -74.01033451806768), emergency_level='BAJA', emergency_type='INTRUSIÓN', description='')
2025-05-16 14:24:39,141 [INFO] night_agent.AGENT009: Tarea recibida: AlertMessage(message_id='c95b4dd2-4037-4208-9744-3ddb607f1830', timestamp=1747398279.1371326, message_type='ALERT', sender_id='SPY019', position=(40.71934207633055, -74.02646782112483), emergency_level='CRÍTICA', emergency_type='INTRUSIÓN', description='')
2025-05-16 14:24:45,920 [INFO] night_agent.AGENT009: Tarea recibida: AlertMessage(message_id='dc97cefd-933e-4bde-8eb6-0ebb8fb7197e', timestamp=1747398285.9156032, message_type='ALERT', sender_id='SPY020', position=(40.7, -73.99537578246334), emergency_level='CRÍTICA', emergency_type='ROBO', description='')
2025-05-16 14:24:51,071 [INFO] night_agent.AGENT009: Tarea recibida: AlertMessage(message_id='17dc02d8-c33b-4f52-bd86-47b9eacc6b33', timestamp=1747398291.06545, message_type='ALERT', sender_id='SPY005', position=(40.7081036260905, -73.96650418069844), emergency_level='MEDIA', emergency_type='SECUESTRO', description='')
2025-05-16 14:24:56,533 [INFO] night_agent.AGENT009: Tarea recibida: AlertMessage(message_id='41f70f1d-b624-44f4-b47c-69fe88ba3dd0', timestamp=1747398296.5285845, message_type='ALERT', sender_id='SPY003', position=(40.70997679216948, -73.96565530578167), emergency_level='CRÍTICA', emergency_type='INTRUSIÓN', description='')
2025-05-16 14:25:04,450 [INFO] night_agent.AGENT009: Tarea recibida: AlertMessage(message_id='df30e4d3-11f8-4f85-b679-461c1d17e4f0', timestamp=1747398304.4466877, message_type='ALERT', sender_id='SPY008', position=(40.79348837161655, -73.99382967570982), emergency_level='BAJA', emergency_type='AMENAZA_BOMBA', description='')
2025-05-16 14:25:09,322 [INFO] night_agent.AGENT009: Tarea recibida: AlertMessage(message_id='d06abe4e-c118-4e4d-a8f4-b9cb3a152699', timestamp=1747398309.3183093, message_type='ALERT', sender_id='SPY016', position=(40.703320506412474, -73.95545432044949), emergency_level='MEDIA', emergency_type='VIGILANCIA', description='')
2025-05-16 14:25:15,897 [INFO] night_agent.AGENT009: Tarea recibida: AlertMessage(message_id='e4081ab7-eecb-4426-8146-827165a6d3de', timestamp=1747398315.8928974, message_type='ALERT', sender_id='SPY012', position=(40.797040238135835, -73.9862534469074), emergency_level='ALTA', emergency_type='INTRUSIÓN', description='')
2025-05-16 14:25:20,094 [INFO] night_agent.AGENT009: Tarea recibida: AlertMessage(message_id='f020c4c3-278a-4f92-979b-5611226150a8', timestamp=1747398320.0893645, message_type='ALERT', sender_id='SPY018', position=(40.72834777261677, -73.95996094409128), emergency_level='MEDIA', emergency_type='SECUESTRO', description='')
2025-05-16 14:25:20,100 [INFO] night_agent.AGENT009: Tarea recibida: AlertMessage(message_id='70c8322f-ffed-4ce5-8cc3-c00a61e60b8e', timestamp=1747398320.0893517, message_type='ALERT', sender_id='SPY009', position=(40.776101078428304, -73.98100785173999), emergency_level='BAJA', emergency_type='SECUESTRO', description='')
