2025-05-15 20:38:23,226 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.718153°N, 73.983721°W
2025-05-15 20:38:28,364 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-15 20:51:39,717 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.799477°N, 73.988177°W
2025-05-15 20:51:39,870 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-15 21:00:54,486 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.705129°N, 74.026388°W
2025-05-15 21:01:04,212 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.765421°N, 73.960762°W
2025-05-15 21:01:04,359 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-15 21:06:28,977 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.728927°N, 74.039584°W
2025-05-15 21:06:29,065 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-15 21:14:17,519 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.705317°N, 74.001243°W
2025-05-15 21:14:17,665 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-15 21:29:39,388 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.714702°N, 73.962700°W
2025-05-15 21:29:39,564 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-15 21:35:03,046 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.751012°N, 74.040504°W
2025-05-15 21:35:03,129 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-15 21:39:40,985 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.744550°N, 74.026639°W
2025-05-15 21:39:41,176 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-15 21:51:33,893 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.718115°N, 73.954507°W
2025-05-15 21:51:34,149 [ERROR] night_agent.AGENT008: Error al conectar con el servidor: name 'RabbitMQConsumer' is not defined
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 81, in connect
    self.comm_client = RabbitMQConsumer(
                       ^^^^^^^^^^^^^^^^
NameError: name 'RabbitMQConsumer' is not defined
2025-05-15 21:51:34,155 [ERROR] night_agent.AGENT008: Error en el agente AGENT008: name 'RabbitMQConsumer' is not defined
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 285, in run
    self.connect()
    ~~~~~~~~~~~~^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 81, in connect
    self.comm_client = RabbitMQConsumer(
                       ^^^^^^^^^^^^^^^^
NameError: name 'RabbitMQConsumer' is not defined
2025-05-15 21:51:34,160 [INFO] night_agent.AGENT008: Deteniendo agente AGENT008
2025-05-15 21:51:34,175 [INFO] night_agent.AGENT008: Cerrada conexión del publisher
2025-05-15 21:51:34,176 [INFO] night_agent.AGENT008: Agente AGENT008 finalizado
2025-05-15 21:53:41,177 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.797591°N, 73.955877°W
2025-05-15 21:53:41,384 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-15 21:57:52,095 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.759262°N, 73.988199°W
2025-05-15 21:57:52,330 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-15 22:07:33,886 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.734944°N, 73.958823°W
2025-05-15 22:07:34,041 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-15 22:25:38,723 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.721286°N, 74.030719°W
2025-05-15 22:25:38,829 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-15 22:27:42,456 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.768337°N, 74.040582°W
2025-05-15 22:27:42,731 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-15 22:31:42,201 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.793717°N, 73.993644°W
2025-05-15 22:31:42,398 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-15 22:48:42,516 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.721093°N, 73.994899°W
2025-05-15 22:48:42,601 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-15 22:54:57,755 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.760582°N, 73.970812°W
2025-05-15 22:54:57,830 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-15 23:04:42,681 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.764546°N, 73.996017°W
2025-05-15 23:04:42,776 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-15 23:10:10,532 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.729357°N, 74.029379°W
2025-05-15 23:10:10,663 [ERROR] night_agent.AGENT008: Error al conectar con el servidor: RabbitMQConsumer.__init__() got an unexpected keyword argument 'auto_ack'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 61, in connect
    self.comm_client = RabbitMQConsumer(
                       ~~~~~~~~~~~~~~~~^
        host=config.RABBITMQ_HOST,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
        auto_ack=False  # Importante: no confirmar automáticamente
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
TypeError: RabbitMQConsumer.__init__() got an unexpected keyword argument 'auto_ack'
2025-05-15 23:10:10,668 [ERROR] night_agent.AGENT008: Error en el agente AGENT008: RabbitMQConsumer.__init__() got an unexpected keyword argument 'auto_ack'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 253, in run
    self.connect()
    ~~~~~~~~~~~~^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 61, in connect
    self.comm_client = RabbitMQConsumer(
                       ~~~~~~~~~~~~~~~~^
        host=config.RABBITMQ_HOST,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
        auto_ack=False  # Importante: no confirmar automáticamente
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
TypeError: RabbitMQConsumer.__init__() got an unexpected keyword argument 'auto_ack'
2025-05-15 23:10:10,669 [INFO] night_agent.AGENT008: Deteniendo agente AGENT008
2025-05-15 23:10:10,679 [INFO] night_agent.AGENT008: Cerrada conexión del publisher
2025-05-15 23:10:10,679 [INFO] night_agent.AGENT008: Agente AGENT008 finalizado
2025-05-15 23:25:17,416 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.773044°N, 74.009497°W
2025-05-15 23:25:17,587 [ERROR] night_agent.AGENT008: Error al conectar con el servidor: RabbitMQConsumer.__init__() got an unexpected keyword argument 'auto_ack'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 61, in connect
    self.comm_client = RabbitMQConsumer(
                       ~~~~~~~~~~~~~~~~^
        host=config.RABBITMQ_HOST,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
        auto_ack=False  # Importante: no confirmar automáticamente
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
TypeError: RabbitMQConsumer.__init__() got an unexpected keyword argument 'auto_ack'
2025-05-15 23:25:17,590 [ERROR] night_agent.AGENT008: Error en el agente AGENT008: RabbitMQConsumer.__init__() got an unexpected keyword argument 'auto_ack'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 253, in run
    self.connect()
    ~~~~~~~~~~~~^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 61, in connect
    self.comm_client = RabbitMQConsumer(
                       ~~~~~~~~~~~~~~~~^
        host=config.RABBITMQ_HOST,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
        auto_ack=False  # Importante: no confirmar automáticamente
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
TypeError: RabbitMQConsumer.__init__() got an unexpected keyword argument 'auto_ack'
2025-05-15 23:25:17,591 [INFO] night_agent.AGENT008: Deteniendo agente AGENT008
2025-05-15 23:25:17,630 [INFO] night_agent.AGENT008: Cerrada conexión del publisher
2025-05-15 23:25:17,630 [INFO] night_agent.AGENT008: Agente AGENT008 finalizado
2025-05-15 23:30:59,116 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.744977°N, 73.986769°W
2025-05-15 23:30:59,262 [ERROR] night_agent.AGENT008: Error al conectar con el servidor: RabbitMQConsumer.__init__() got an unexpected keyword argument 'auto_ack'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 61, in connect
    self.comm_client = RabbitMQConsumer(
                       ~~~~~~~~~~~~~~~~^
        host=config.RABBITMQ_HOST,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
        auto_ack=False  # Importante: no confirmar automáticamente
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
TypeError: RabbitMQConsumer.__init__() got an unexpected keyword argument 'auto_ack'
2025-05-15 23:30:59,264 [ERROR] night_agent.AGENT008: Error en el agente AGENT008: RabbitMQConsumer.__init__() got an unexpected keyword argument 'auto_ack'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 253, in run
    self.connect()
    ~~~~~~~~~~~~^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 61, in connect
    self.comm_client = RabbitMQConsumer(
                       ~~~~~~~~~~~~~~~~^
        host=config.RABBITMQ_HOST,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
        auto_ack=False  # Importante: no confirmar automáticamente
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
TypeError: RabbitMQConsumer.__init__() got an unexpected keyword argument 'auto_ack'
2025-05-15 23:30:59,265 [INFO] night_agent.AGENT008: Deteniendo agente AGENT008
2025-05-15 23:30:59,296 [INFO] night_agent.AGENT008: Cerrada conexión del publisher
2025-05-15 23:30:59,296 [INFO] night_agent.AGENT008: Agente AGENT008 finalizado
2025-05-15 23:32:43,797 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.788593°N, 73.964457°W
2025-05-15 23:32:44,034 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-15 23:32:44,034 [ERROR] night_agent.AGENT008: Error en el agente AGENT008: 'NoneType' object has no attribute 'basic_qos'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 257, in run
    self.comm_client.channel.basic_qos(prefetch_count=1)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'basic_qos'
2025-05-15 23:32:44,036 [INFO] night_agent.AGENT008: Deteniendo agente AGENT008
2025-05-15 23:32:44,036 [INFO] night_agent.AGENT008: Desconectado del servidor
2025-05-15 23:32:44,044 [INFO] night_agent.AGENT008: Cerrada conexión del publisher
2025-05-15 23:32:44,044 [INFO] night_agent.AGENT008: Agente AGENT008 finalizado
2025-05-15 23:34:56,228 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.740641°N, 73.969076°W
2025-05-15 23:34:56,414 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-15 23:36:19,482 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.733538°N, 74.049991°W
2025-05-15 23:36:19,743 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-15 23:38:13,602 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.713752°N, 73.971934°W
2025-05-15 23:38:13,817 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-15 23:40:03,693 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.778363°N, 73.979566°W
2025-05-15 23:40:03,876 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-15 23:43:11,765 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.765568°N, 74.035677°W
2025-05-15 23:43:11,854 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-15 23:46:38,754 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.752785°N, 74.020822°W
2025-05-15 23:46:38,968 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-15 23:50:02,008 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.776575°N, 73.952873°W
2025-05-15 23:50:02,165 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-15 23:55:36,229 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.729979°N, 73.954957°W
2025-05-15 23:55:36,351 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-15 23:59:48,580 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.778967°N, 73.986365°W
2025-05-15 23:59:48,769 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-16 00:05:21,325 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.720147°N, 73.986377°W
2025-05-16 00:05:21,439 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-16 00:13:10,462 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.740478°N, 73.978343°W
2025-05-16 00:13:10,544 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-16 00:13:10,544 [ERROR] night_agent.AGENT008: Error en el agente AGENT008: 'NoneType' object has no attribute 'start_consuming'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 245, in run
    self.comm_client.start_consuming(callback=self.handle_task)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'start_consuming'
2025-05-16 00:13:10,547 [INFO] night_agent.AGENT008: Deteniendo agente AGENT008
2025-05-16 00:13:10,552 [INFO] night_agent.AGENT008: Cerrada conexión del publisher
2025-05-16 00:13:10,553 [INFO] night_agent.AGENT008: Agente AGENT008 finalizado
2025-05-16 00:18:17,263 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.764713°N, 74.037581°W
2025-05-16 00:18:17,554 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-16 00:22:02,488 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.775091°N, 74.011154°W
2025-05-16 00:22:02,621 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-16 00:24:21,730 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.771530°N, 74.037694°W
2025-05-16 00:24:22,090 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-16 00:28:44,335 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.748897°N, 74.000716°W
2025-05-16 00:28:44,662 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-16 00:28:44,672 [ERROR] night_agent.AGENT008: Error al enviar estado: 'NoneType' object has no attribute 'publish_message'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 96, in send_status_update
    self.publisher.publish_message(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'publish_message'
2025-05-16 00:33:49,686 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.714914°N, 73.974147°W
2025-05-16 00:33:49,888 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-16 00:33:49,913 [ERROR] night_agent.AGENT008: Error al enviar estado: 'NoneType' object has no attribute 'publish_message'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 96, in send_status_update
    self.publisher.publish_message(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'publish_message'
2025-05-16 00:35:21,581 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.726147°N, 74.018993°W
2025-05-16 00:35:21,712 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-16 00:35:21,727 [ERROR] night_agent.AGENT008: Error al enviar estado: 'NoneType' object has no attribute 'publish_message'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 96, in send_status_update
    self.publisher.publish_message(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'publish_message'
2025-05-16 09:43:05,303 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.766594°N, 74.023561°W
2025-05-16 09:43:05,494 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-16 09:43:05,504 [ERROR] night_agent.AGENT008: Error al enviar estado: 'NoneType' object has no attribute 'publish_message'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 95, in send_status_update
    self.publisher.publish_message(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'publish_message'
2025-05-16 10:00:02,876 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.728775°N, 73.974299°W
2025-05-16 10:00:03,008 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-16 10:00:03,018 [ERROR] night_agent.AGENT008: Error al enviar estado: 'NoneType' object has no attribute 'publish_message'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 94, in send_status_update
    self.publisher.publish_message(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'publish_message'
2025-05-16 10:08:24,534 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.712117°N, 74.044956°W
2025-05-16 10:08:24,602 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-16 10:08:24,604 [ERROR] night_agent.AGENT008: Error al enviar estado: 'NoneType' object has no attribute 'publish_message'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 94, in send_status_update
    self.publisher.publish_message(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'publish_message'
2025-05-16 10:14:26,735 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.748139°N, 73.956108°W
2025-05-16 10:14:26,736 [ERROR] night_agent.AGENT008: Error al conectar con el servidor: RabbitMQConsumer.__init__() got an unexpected keyword argument 'on_message_callback'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 50, in connect
    self.comm_client = RabbitMQConsumer(
                       ~~~~~~~~~~~~~~~~^
        host=config.RABBITMQ_HOST,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
        binding_keys=['task.broadcast']
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
TypeError: RabbitMQConsumer.__init__() got an unexpected keyword argument 'on_message_callback'
2025-05-16 10:14:26,738 [ERROR] night_agent.AGENT008: Error en el agente AGENT008: RabbitMQConsumer.__init__() got an unexpected keyword argument 'on_message_callback'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 255, in run
    self.connect()
    ~~~~~~~~~~~~^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 50, in connect
    self.comm_client = RabbitMQConsumer(
                       ~~~~~~~~~~~~~~~~^
        host=config.RABBITMQ_HOST,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
        binding_keys=['task.broadcast']
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
TypeError: RabbitMQConsumer.__init__() got an unexpected keyword argument 'on_message_callback'
2025-05-16 10:14:26,739 [INFO] night_agent.AGENT008: Deteniendo agente AGENT008
2025-05-16 10:14:26,739 [INFO] night_agent.AGENT008: Agente AGENT008 finalizado
2025-05-16 10:19:54,191 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.733446°N, 73.986847°W
2025-05-16 10:19:54,191 [ERROR] night_agent.AGENT008: Error al conectar con el servidor: RabbitMQConsumer.__init__() got an unexpected keyword argument 'on_message_callback'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 50, in connect
    self.comm_client = RabbitMQConsumer(
                       ~~~~~~~~~~~~~~~~^
        host=config.RABBITMQ_HOST,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
        binding_keys=['task.broadcast']
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
TypeError: RabbitMQConsumer.__init__() got an unexpected keyword argument 'on_message_callback'
2025-05-16 10:19:54,193 [ERROR] night_agent.AGENT008: Error en el agente AGENT008: RabbitMQConsumer.__init__() got an unexpected keyword argument 'on_message_callback'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 262, in run
    self.connect()
    ~~~~~~~~~~~~^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 50, in connect
    self.comm_client = RabbitMQConsumer(
                       ~~~~~~~~~~~~~~~~^
        host=config.RABBITMQ_HOST,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
        binding_keys=['task.broadcast']
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
TypeError: RabbitMQConsumer.__init__() got an unexpected keyword argument 'on_message_callback'
2025-05-16 10:19:54,194 [INFO] night_agent.AGENT008: Deteniendo agente AGENT008
2025-05-16 10:19:54,194 [INFO] night_agent.AGENT008: Agente AGENT008 finalizado
2025-05-16 10:22:12,974 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.769352°N, 73.984965°W
2025-05-16 10:22:13,154 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-16 10:22:13,155 [ERROR] night_agent.AGENT008: Error al enviar estado: 'NoneType' object has no attribute 'publish_message'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 117, in send_status_update
    self.publisher.publish_message(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'publish_message'
2025-05-16 10:28:21,197 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.712408°N, 74.015800°W
2025-05-16 10:28:21,360 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-16 10:28:21,360 [ERROR] night_agent.AGENT008: Error al enviar estado: 'NoneType' object has no attribute 'publish_message'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 118, in send_status_update
    self.publisher.publish_message(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'publish_message'
2025-05-16 10:36:28,533 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.716895°N, 73.966155°W
2025-05-16 10:36:28,825 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-16 10:36:28,826 [ERROR] night_agent.AGENT008: Error al enviar estado: cannot access local variable 'properties' where it is not associated with a value
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 151, in send_status_update
    self.publisher.publish_message(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        message,
        ^^^^^^^^
        routing_key='task.broadcast'
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 135, in publish_message
    properties=properties
               ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'properties' where it is not associated with a value
2025-05-16 10:39:56,569 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.700949°N, 73.984054°W
2025-05-16 10:39:56,801 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-16 10:44:23,911 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.748650°N, 73.973499°W
2025-05-16 10:44:24,279 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-16 10:47:57,315 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.771676°N, 73.954927°W
2025-05-16 10:47:57,620 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-16 10:47:57,665 [ERROR] night_agent.AGENT008: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:47:57,668 [ERROR] night_agent.AGENT008: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:47:57,784 [ERROR] night_agent.AGENT008: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:47:57,785 [ERROR] night_agent.AGENT008: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:48:10,289 [ERROR] night_agent.AGENT008: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:48:10,290 [ERROR] night_agent.AGENT008: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:48:16,698 [ERROR] night_agent.AGENT008: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:48:16,699 [ERROR] night_agent.AGENT008: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:48:20,043 [ERROR] night_agent.AGENT008: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:48:20,044 [ERROR] night_agent.AGENT008: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:48:29,588 [ERROR] night_agent.AGENT008: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:48:29,589 [ERROR] night_agent.AGENT008: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:48:35,151 [ERROR] night_agent.AGENT008: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:48:35,152 [ERROR] night_agent.AGENT008: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:48:41,886 [ERROR] night_agent.AGENT008: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:48:41,887 [ERROR] night_agent.AGENT008: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:48:49,411 [ERROR] night_agent.AGENT008: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:48:49,412 [ERROR] night_agent.AGENT008: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:48:55,263 [ERROR] night_agent.AGENT008: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:48:55,264 [ERROR] night_agent.AGENT008: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:49:00,316 [ERROR] night_agent.AGENT008: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:49:00,317 [ERROR] night_agent.AGENT008: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:49:07,182 [ERROR] night_agent.AGENT008: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:49:07,183 [ERROR] night_agent.AGENT008: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:49:12,839 [ERROR] night_agent.AGENT008: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:49:12,841 [ERROR] night_agent.AGENT008: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:49:19,025 [ERROR] night_agent.AGENT008: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:49:19,026 [ERROR] night_agent.AGENT008: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:49:24,981 [ERROR] night_agent.AGENT008: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:49:24,982 [ERROR] night_agent.AGENT008: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:49:33,277 [ERROR] night_agent.AGENT008: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:49:33,277 [ERROR] night_agent.AGENT008: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:49:38,297 [ERROR] night_agent.AGENT008: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:49:38,298 [ERROR] night_agent.AGENT008: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:49:43,799 [ERROR] night_agent.AGENT008: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:49:43,800 [ERROR] night_agent.AGENT008: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:49:51,066 [ERROR] night_agent.AGENT008: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:49:51,067 [ERROR] night_agent.AGENT008: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:49:57,503 [ERROR] night_agent.AGENT008: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:49:57,503 [ERROR] night_agent.AGENT008: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:50:03,227 [ERROR] night_agent.AGENT008: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:50:03,228 [ERROR] night_agent.AGENT008: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:50:09,713 [ERROR] night_agent.AGENT008: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:50:09,713 [ERROR] night_agent.AGENT008: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:50:17,486 [ERROR] night_agent.AGENT008: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:50:17,487 [ERROR] night_agent.AGENT008: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:50:23,833 [ERROR] night_agent.AGENT008: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:50:23,834 [ERROR] night_agent.AGENT008: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:50:29,726 [ERROR] night_agent.AGENT008: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:50:29,726 [ERROR] night_agent.AGENT008: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:50:37,760 [ERROR] night_agent.AGENT008: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:50:37,760 [ERROR] night_agent.AGENT008: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:50:43,226 [ERROR] night_agent.AGENT008: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:50:43,227 [ERROR] night_agent.AGENT008: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:50:49,150 [ERROR] night_agent.AGENT008: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:50:49,150 [ERROR] night_agent.AGENT008: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:50:50,904 [ERROR] night_agent.AGENT008: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:50:50,912 [ERROR] night_agent.AGENT008: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:50:50,921 [ERROR] night_agent.AGENT008: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:50:50,928 [ERROR] night_agent.AGENT008: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:50:56,960 [ERROR] night_agent.AGENT008: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:50:56,961 [ERROR] night_agent.AGENT008: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:51:04,055 [ERROR] night_agent.AGENT008: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:51:04,056 [ERROR] night_agent.AGENT008: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:51:09,434 [ERROR] night_agent.AGENT008: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:51:09,435 [ERROR] night_agent.AGENT008: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:51:17,610 [ERROR] night_agent.AGENT008: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:51:17,611 [ERROR] night_agent.AGENT008: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:51:23,543 [ERROR] night_agent.AGENT008: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:51:23,544 [ERROR] night_agent.AGENT008: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:51:29,616 [ERROR] night_agent.AGENT008: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:51:29,616 [ERROR] night_agent.AGENT008: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:51:34,211 [ERROR] night_agent.AGENT008: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:51:34,212 [ERROR] night_agent.AGENT008: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:51:43,509 [ERROR] night_agent.AGENT008: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:51:43,510 [ERROR] night_agent.AGENT008: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:51:47,270 [ERROR] night_agent.AGENT008: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:51:47,271 [ERROR] night_agent.AGENT008: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:51:55,492 [ERROR] night_agent.AGENT008: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:51:55,492 [ERROR] night_agent.AGENT008: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:52:00,888 [ERROR] night_agent.AGENT008: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:52:00,889 [ERROR] night_agent.AGENT008: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:52:07,800 [ERROR] night_agent.AGENT008: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:52:07,801 [ERROR] night_agent.AGENT008: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:52:13,738 [ERROR] night_agent.AGENT008: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:52:13,738 [ERROR] night_agent.AGENT008: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    task = Message.from_json(task_json)
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
    self.publisher.publish_message(task_json, routing_key="tasks.unprocessed")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:52:19,706 [ERROR] night_agent.AGENT008: Error procesando tarea: Message.__init__() got an unexpected keyword argument 'position'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    safe_sleep(move_time)
           ~~~^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'
2025-05-16 10:52:19,707 [ERROR] night_agent.AGENT008: Error al reenviar la tarea: 'str' object has no attribute 'to_json'
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 186, in handle_task
    safe_sleep(move_time)
           ~~~^^^^^^^^^^^
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\common\message.py", line 27, in from_json
    return cls(**data)
TypeError: Message.__init__() got an unexpected keyword argument 'position'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 226, in requeue_task
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\communication\rabbitmq\publisher.py", line 120, in publish_message
    serialized_message = message.to_json().encode("utf-8")
                         ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_json'
2025-05-16 10:53:21,718 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.741588°N, 74.026845°W
2025-05-16 10:53:21,950 [ERROR] night_agent.AGENT008: Error procesando tarea: name 'create_message_from_json' is not defined
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 129, in handle_task
    task = create_message_from_json(task_json)
           ^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'create_message_from_json' is not defined
2025-05-16 10:53:21,974 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-16 10:53:29,640 [ERROR] night_agent.AGENT008: Error procesando tarea: name 'create_message_from_json' is not defined
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 129, in handle_task
    task = create_message_from_json(task_json)
           ^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'create_message_from_json' is not defined
2025-05-16 10:53:30,061 [ERROR] night_agent.AGENT008: Error procesando tarea: name 'create_message_from_json' is not defined
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 129, in handle_task
    task = create_message_from_json(task_json)
           ^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'create_message_from_json' is not defined
2025-05-16 10:53:30,069 [ERROR] night_agent.AGENT008: Error procesando tarea: name 'create_message_from_json' is not defined
Traceback (most recent call last):
  File "C:\Users\alexb\Documents\UAX\2_Ing\Metodos Numericos\ULab\PythonProject\agents\night_agent.py", line 129, in handle_task
    task = create_message_from_json(task_json)
           ^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'create_message_from_json' is not defined
2025-05-16 10:55:36,978 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.752642°N, 73.968527°W
2025-05-16 10:55:37,188 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-16 10:55:37,195 [INFO] night_agent.AGENT008: Tarea recibida: AlertMessage(message_id='2f759306-7623-4168-b56a-8e0e9faa752a', timestamp=1747385737.1504118, message_type='ALERT', sender_id='SPY018', position=(40.720313, -74.01742), emergency_level='ALTA', emergency_type='VIGILANCIA', description='')
2025-05-16 10:55:48,911 [INFO] night_agent.AGENT008: Tarea recibida: AlertMessage(message_id='5c94a7d3-26c8-4746-8084-85096a44654f', timestamp=1747385748.909101, message_type='ALERT', sender_id='SPY009', position=(40.7246566235385, -73.98282189341725), emergency_level='CRÍTICA', emergency_type='SECUESTRO', description='')
2025-05-16 10:55:55,321 [INFO] night_agent.AGENT008: Tarea recibida: AlertMessage(message_id='a0a02db0-3683-4d75-8ab3-5171a9ae0ce2', timestamp=1747385755.3184443, message_type='ALERT', sender_id='SPY001', position=(40.759548498806325, -74.01376315152565), emergency_level='BAJA', emergency_type='ROBO', description='')
2025-05-16 10:56:02,100 [INFO] night_agent.AGENT008: Tarea recibida: AlertMessage(message_id='18b79087-d1fa-403e-a0ee-df7c93ea0440', timestamp=1747385762.097543, message_type='ALERT', sender_id='SPY003', position=(40.71727138951725, -73.99667491616277), emergency_level='CRÍTICA', emergency_type='ROBO', description='')
2025-05-16 10:56:06,004 [INFO] night_agent.AGENT008: Tarea recibida: AlertMessage(message_id='567f2b5b-ab5b-4652-abd7-9bf59b5b41f3', timestamp=1747385766.0019507, message_type='ALERT', sender_id='SPY009', position=(40.72394806484996, -73.98210300030144), emergency_level='ALTA', emergency_type='SECUESTRO', description='')
2025-05-16 10:56:12,351 [INFO] night_agent.AGENT008: Tarea recibida: AlertMessage(message_id='b97f320a-06cd-485c-9850-99376fe2271c', timestamp=1747385772.3495502, message_type='ALERT', sender_id='SPY008', position=(40.70603564787901, -74.03170995122255), emergency_level='ALTA', emergency_type='VIGILANCIA', description='')
2025-05-16 10:56:16,218 [INFO] night_agent.AGENT008: Tarea recibida: AlertMessage(message_id='10b8682c-f205-4181-9e2e-0060107b7c50', timestamp=1747385776.2125635, message_type='ALERT', sender_id='SPY018', position=(40.719717342842436, -74.0176655718522), emergency_level='CRÍTICA', emergency_type='VIGILANCIA', description='')
2025-05-16 10:56:16,224 [INFO] night_agent.AGENT008: Tarea recibida: AlertMessage(message_id='103e83cf-e7fb-4352-bc9c-7f953851eee1', timestamp=1747385776.2142208, message_type='ALERT', sender_id='SPY003', position=(40.71679486280367, -73.99572339872235), emergency_level='MEDIA', emergency_type='SECUESTRO', description='')
2025-05-16 14:21:44,913 [INFO] night_agent.AGENT008: Agente AGENT008 inicializado en posición 40.789356°N, 73.959442°W
2025-05-16 14:21:45,154 [INFO] night_agent.AGENT008: Conectado al servidor usando rabbitmq
2025-05-16 14:21:45,285 [INFO] night_agent.AGENT008: Tarea recibida: AlertMessage(message_id='14267632-5be7-43a1-96d9-3998fb8d6c0d', timestamp=1747398105.225498, message_type='ALERT', sender_id='SPY018', position=(40.731636, -73.95914), emergency_level='ALTA', emergency_type='AMENAZA_BOMBA', description='')
2025-05-16 14:21:53,192 [INFO] night_agent.AGENT008: Tarea recibida: AlertMessage(message_id='1baa6e85-d9c9-45a4-9417-1f6a04b5626f', timestamp=1747398113.1883526, message_type='ALERT', sender_id='SPY003', position=(40.71426092754043, -73.96465219126506), emergency_level='ALTA', emergency_type='INTRUSIÓN', description='')
2025-05-16 14:22:00,730 [INFO] night_agent.AGENT008: Tarea recibida: AlertMessage(message_id='eac426fd-2a3c-401a-b7c8-7d55995df0d6', timestamp=1747398120.7264838, message_type='ALERT', sender_id='SPY013', position=(40.76846434445812, -74.02595209037958), emergency_level='BAJA', emergency_type='INTRUSIÓN', description='')
2025-05-16 14:22:03,265 [INFO] night_agent.AGENT008: Tarea recibida: AlertMessage(message_id='f827796a-e579-49ad-89ff-37517670f97d', timestamp=1747398123.2611666, message_type='ALERT', sender_id='SPY010', position=(40.76512678132085, -73.99866427578247), emergency_level='CRÍTICA', emergency_type='SECUESTRO', description='')
2025-05-16 14:22:10,743 [INFO] night_agent.AGENT008: Tarea recibida: AlertMessage(message_id='a9446ec4-fd60-43eb-8666-03507a58e13b', timestamp=1747398130.7393916, message_type='ALERT', sender_id='SPY012', position=(40.79837949034694, -73.98446246724971), emergency_level='ALTA', emergency_type='VIGILANCIA', description='')
2025-05-16 14:22:17,146 [INFO] night_agent.AGENT008: Tarea recibida: AlertMessage(message_id='40254bfc-1f4d-4228-88d2-fc8206c932f6', timestamp=1747398137.1423666, message_type='ALERT', sender_id='SPY004', position=(40.73204263085345, -73.98479384699336), emergency_level='MEDIA', emergency_type='INTRUSIÓN', description='')
2025-05-16 14:22:21,354 [INFO] night_agent.AGENT008: Tarea recibida: AlertMessage(message_id='c3a170f2-43e6-454d-8431-9f9a832a8c71', timestamp=1747398141.3497825, message_type='ALERT', sender_id='SPY013', position=(40.768253612479754, -74.02642499463903), emergency_level='CRÍTICA', emergency_type='INTRUSIÓN', description='')
2025-05-16 14:22:28,883 [INFO] night_agent.AGENT008: Tarea recibida: AlertMessage(message_id='00094777-0803-4074-a134-3b523159131c', timestamp=1747398148.8785203, message_type='ALERT', sender_id='SPY013', position=(40.768925226831286, -74.02707077903194), emergency_level='CRÍTICA', emergency_type='SECUESTRO', description='')
2025-05-16 14:22:35,416 [INFO] night_agent.AGENT008: Tarea recibida: AlertMessage(message_id='efdc54eb-0a50-46f3-80c2-9cc9fe81ce50', timestamp=1747398155.4124918, message_type='ALERT', sender_id='SPY020', position=(40.701707011537664, -74.00016904319601), emergency_level='MEDIA', emergency_type='ROBO', description='')
2025-05-16 14:22:38,831 [INFO] night_agent.AGENT008: Tarea recibida: AlertMessage(message_id='032ce998-2be4-4c39-af55-bc621499739b', timestamp=1747398158.8273838, message_type='ALERT', sender_id='SPY009', position=(40.7763088936289, -73.97937970829507), emergency_level='MEDIA', emergency_type='VIGILANCIA', description='')
2025-05-16 14:22:46,633 [INFO] night_agent.AGENT008: Tarea recibida: AlertMessage(message_id='a12c6e09-18f5-468a-9fe3-0b6394e0c381', timestamp=1747398166.6293423, message_type='ALERT', sender_id='SPY017', position=(40.752182804077805, -74.02116795815833), emergency_level='ALTA', emergency_type='VIGILANCIA', description='')
2025-05-16 14:22:51,726 [INFO] night_agent.AGENT008: Tarea recibida: AlertMessage(message_id='f2deca87-da5b-40e0-a505-e8697eb135bb', timestamp=1747398171.7208436, message_type='ALERT', sender_id='SPY012', position=(40.79876631936979, -73.98531582907684), emergency_level='ALTA', emergency_type='INTRUSIÓN', description='')
2025-05-16 14:22:59,123 [INFO] night_agent.AGENT008: Tarea recibida: AlertMessage(message_id='dc190c14-26d2-4962-be92-1a404586d869', timestamp=1747398179.1186957, message_type='ALERT', sender_id='SPY014', position=(40.743367662829925, -73.95113444930021), emergency_level='BAJA', emergency_type='VIGILANCIA', description='')
2025-05-16 14:23:05,553 [INFO] night_agent.AGENT008: Tarea recibida: AlertMessage(message_id='06c3d13f-17a8-45dc-b7fe-92f61301a525', timestamp=1747398185.5483904, message_type='ALERT', sender_id='SPY011', position=(40.781294452861914, -73.99025790237047), emergency_level='CRÍTICA', emergency_type='SECUESTRO', description='')
2025-05-16 14:23:12,676 [INFO] night_agent.AGENT008: Tarea recibida: AlertMessage(message_id='6ea21d69-1654-482c-a8b6-e1dd25e42de7', timestamp=1747398192.671936, message_type='ALERT', sender_id='SPY012', position=(40.799108290504556, -73.98541195665702), emergency_level='ALTA', emergency_type='INTRUSIÓN', description='')
2025-05-16 14:23:17,685 [INFO] night_agent.AGENT008: Tarea recibida: AlertMessage(message_id='48e8356f-8ed1-4739-8e74-b1874287523f', timestamp=1747398197.6811843, message_type='ALERT', sender_id='SPY006', position=(40.70994604171916, -73.9984669389989), emergency_level='ALTA', emergency_type='ROBO', description='')
2025-05-16 14:23:23,622 [INFO] night_agent.AGENT008: Tarea recibida: AlertMessage(message_id='b1b86b12-ed3a-4e27-b752-f4dc6c81d94a', timestamp=1747398203.6179175, message_type='ALERT', sender_id='SPY015', position=(40.71658390693879, -73.97187821181583), emergency_level='MEDIA', emergency_type='AMENAZA_BOMBA', description='')
2025-05-16 14:23:30,863 [INFO] night_agent.AGENT008: Tarea recibida: AlertMessage(message_id='99de3b27-b2fb-4686-8f41-010d01176eb9', timestamp=1747398210.8499722, message_type='ALERT', sender_id='SPY008', position=(40.79364699463455, -73.99381438649543), emergency_level='MEDIA', emergency_type='INTRUSIÓN', description='')
2025-05-16 14:23:38,143 [INFO] night_agent.AGENT008: Tarea recibida: AlertMessage(message_id='653d891a-55d3-4f7f-9375-b60606c79b16', timestamp=1747398218.1390736, message_type='ALERT', sender_id='SPY004', position=(40.73079382013533, -73.98811263097471), emergency_level='CRÍTICA', emergency_type='SECUESTRO', description='')
2025-05-16 14:23:43,458 [INFO] night_agent.AGENT008: Tarea recibida: AlertMessage(message_id='7590770f-1b9f-48c8-bd1a-1d37ed2cb096', timestamp=1747398223.4543607, message_type='ALERT', sender_id='SPY004', position=(40.7301620023093, -73.98824647980763), emergency_level='CRÍTICA', emergency_type='INTRUSIÓN', description='')
2025-05-16 14:23:48,867 [INFO] night_agent.AGENT008: Tarea recibida: AlertMessage(message_id='a4fdbb97-2d27-45f4-8573-364c75c1a084', timestamp=1747398228.8632622, message_type='ALERT', sender_id='SPY005', position=(40.706840930194346, -73.9661979150022), emergency_level='ALTA', emergency_type='ROBO', description='')
2025-05-16 14:23:55,517 [INFO] night_agent.AGENT008: Tarea recibida: AlertMessage(message_id='21743307-a6f6-41cc-8dbb-e56bf6c6cb64', timestamp=1747398235.4725835, message_type='ALERT', sender_id='SPY007', position=(40.737303179152434, -73.96991219092553), emergency_level='MEDIA', emergency_type='VIGILANCIA', description='')
2025-05-16 14:24:02,090 [INFO] night_agent.AGENT008: Tarea recibida: AlertMessage(message_id='27054b7f-764f-4ac9-bb04-3e541037f57f', timestamp=1747398242.0862396, message_type='ALERT', sender_id='SPY004', position=(40.72954259070788, -73.98893452018908), emergency_level='CRÍTICA', emergency_type='AMENAZA_BOMBA', description='')
2025-05-16 14:24:07,231 [INFO] night_agent.AGENT008: Tarea recibida: AlertMessage(message_id='c92847ee-4dcd-4039-a6f9-4cc04b5668b8', timestamp=1747398247.2257357, message_type='ALERT', sender_id='SPY009', position=(40.77618523190921, -73.98139516691765), emergency_level='ALTA', emergency_type='AMENAZA_BOMBA', description='')
2025-05-16 14:24:16,249 [INFO] night_agent.AGENT008: Tarea recibida: AlertMessage(message_id='a44fee32-11d6-49a8-9c2a-b06cd6d62d58', timestamp=1747398256.2458768, message_type='ALERT', sender_id='SPY016', position=(40.70355421051506, -73.95391087801715), emergency_level='BAJA', emergency_type='VIGILANCIA', description='')
2025-05-16 14:24:20,718 [INFO] night_agent.AGENT008: Tarea recibida: AlertMessage(message_id='34dd885e-1ad0-4c46-9c57-3791c64c7415', timestamp=1747398260.7149284, message_type='ALERT', sender_id='SPY010', position=(40.764613616262885, -73.996442256529), emergency_level='BAJA', emergency_type='ROBO', description='')
2025-05-16 14:24:28,764 [INFO] night_agent.AGENT008: Tarea recibida: AlertMessage(message_id='36401c2c-1dcd-4a44-9ff4-fffaa291452d', timestamp=1747398268.7603025, message_type='ALERT', sender_id='SPY014', position=(40.744363751122314, -73.95342132757052), emergency_level='CRÍTICA', emergency_type='INTRUSIÓN', description='')
2025-05-16 14:24:35,046 [INFO] night_agent.AGENT008: Tarea recibida: AlertMessage(message_id='6e7dd751-06b6-413f-9041-9df5ece69994', timestamp=1747398275.042331, message_type='ALERT', sender_id='SPY008', position=(40.79198645167076, -73.99404961519697), emergency_level='ALTA', emergency_type='SECUESTRO', description='')
2025-05-16 14:24:39,192 [INFO] night_agent.AGENT008: Tarea recibida: AlertMessage(message_id='09259d04-ea6f-49d8-b893-d7a9ea99e088', timestamp=1747398279.1885414, message_type='ALERT', sender_id='SPY007', position=(40.737517312990576, -73.9695698438474), emergency_level='ALTA', emergency_type='ROBO', description='')
2025-05-16 14:24:45,954 [INFO] night_agent.AGENT008: Tarea recibida: AlertMessage(message_id='1ab3757e-f3f2-4165-b4da-1020aa305fd6', timestamp=1747398285.9455295, message_type='ALERT', sender_id='SPY010', position=(40.765140005725634, -73.99699650883427), emergency_level='CRÍTICA', emergency_type='AMENAZA_BOMBA', description='')
2025-05-16 14:24:51,383 [INFO] night_agent.AGENT008: Tarea recibida: AlertMessage(message_id='77fbf06f-056e-4747-ae53-ecbd8840c14e', timestamp=1747398291.3785946, message_type='ALERT', sender_id='SPY020', position=(40.70025609606286, -73.99459281136394), emergency_level='CRÍTICA', emergency_type='AMENAZA_BOMBA', description='')
2025-05-16 14:24:57,337 [INFO] night_agent.AGENT008: Tarea recibida: AlertMessage(message_id='1321aacd-0649-4a73-b552-bd6d0b6767dd', timestamp=1747398297.3336897, message_type='ALERT', sender_id='SPY011', position=(40.78151680370987, -73.99207830349256), emergency_level='BAJA', emergency_type='AMENAZA_BOMBA', description='')
2025-05-16 14:25:05,264 [INFO] night_agent.AGENT008: Tarea recibida: AlertMessage(message_id='a3c0e2b4-d2f0-4963-9098-e47096ca1c4c', timestamp=1747398305.2599196, message_type='ALERT', sender_id='SPY020', position=(40.7, -73.99491220194058), emergency_level='CRÍTICA', emergency_type='VIGILANCIA', description='')
2025-05-16 14:25:09,967 [INFO] night_agent.AGENT008: Tarea recibida: AlertMessage(message_id='a6b622cb-9bf6-40d1-bcb8-6d4d432bd1aa', timestamp=1747398309.9495246, message_type='ALERT', sender_id='SPY006', position=(40.71023505172206, -73.99668364646749), emergency_level='CRÍTICA', emergency_type='AMENAZA_BOMBA', description='')
2025-05-16 14:25:16,538 [INFO] night_agent.AGENT008: Tarea recibida: AlertMessage(message_id='4f460594-bc7b-4cea-b1dc-1038236b2a9a', timestamp=1747398316.5334272, message_type='ALERT', sender_id='SPY014', position=(40.74516391639553, -73.95508012760652), emergency_level='CRÍTICA', emergency_type='INTRUSIÓN', description='')
2025-05-16 14:25:20,094 [INFO] night_agent.AGENT008: Tarea recibida: AlertMessage(message_id='49e71d87-6903-4d8b-ab9f-aff7660b1d6b', timestamp=1747398320.0897236, message_type='ALERT', sender_id='SPY015', position=(40.71686771609459, -73.97041460768278), emergency_level='BAJA', emergency_type='ROBO', description='')
2025-05-16 14:25:20,101 [INFO] night_agent.AGENT008: Tarea recibida: AlertMessage(message_id='fcc6d7c2-7606-437d-839d-6cb34784f721', timestamp=1747398320.089538, message_type='ALERT', sender_id='SPY016', position=(40.703071195625334, -73.95565726834705), emergency_level='CRÍTICA', emergency_type='ROBO', description='')
